#!/usr/bin/env python3.5

from selenium import webdriver

import time

url = "https://www.wileyplus.com/"

driver = webdriver.Firefox()
driver.get(url)
driver.maximize_window()
time.sleep(3)
driver.find_element_by_link_text("Login").click()
driver.find_element_by_css_selector("a[class='wp-secondary-btn']").click()
time.sleep(4)
driver.find_element_by_css_selector("input[id='email']").send_keys("jareddyreson@csu.fullerton.edu")
# wiley plus won't let me fill in a password. great fucking job.
